
package gui;

import oop.classes.actors.User;
    //Java Swing Components
import javax.swing.*; //note to self: * means wildcard
    //imports all classes inside java.awt (like Font & BorderLayout)
import java.awt.*;
import oop.classes.actors.User;


//public class EmployeeSelfService extends javax.swing.JFrame { --> no need to specify javax.swing.* since it was already impored up there!
public class Admin extends JFrame {
    private User loggedInUser; //to store logged in user's data so we can display it in the gui
    private User user; //store user info so it can be accessed anywhere in the class
    private JLabel lblEmployeeUser; //declared to remove lblEmployeeUser error, bec it needs a jlabel variable
    public Admin(User user) {
        
        
        setTitle("MotorPH Admin Dashboard | Welcome, " + user.getFirstName() + " " + user.getLastName() + "!");
        // Update the label inside the UI with the user's name
        // Check if lblEmployeeUser is initialized before setting text
        if (lblWelcomeMessage != null) {
            lblWelcomeMessage.setText(user.getFirstName() + " " + user.getLastName());
        } else {
            System.out.println("Error: lblWelcomeMessage is null. Check NetBeans GUI Builder.");
        }
        
        initComponents();
        this.loggedInUser = user; //keeping track of who's logged in so we can show the right info
        
        

        // Set window properties
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  // Close program when window is closed
        this.pack();  // Automatically sizes the JFrame based on components
        this.setLocationRelativeTo(null);  // Centers the window on the screen

        setLayout(new BorderLayout());  // Use BorderLayout for better organization

    }  
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        emppagemainPNL = new javax.swing.JPanel();
        emppagemenuPNL = new javax.swing.JPanel();
        specialaccessPNL = new javax.swing.JPanel();
        dateTime = new javax.swing.JLabel();
        employeepagenameLBL = new javax.swing.JLabel();
        logoutemppgPB = new javax.swing.JButton();
        aboutPB = new javax.swing.JButton();
        personaldetPB = new javax.swing.JButton();
        attendanceemppgPB = new javax.swing.JButton();
        payrollemppgPB = new javax.swing.JButton();
        requestleaveemppgPB = new javax.swing.JButton();
        redOrangeDesign = new javax.swing.JLabel();
        lblWelcomeMessage = new javax.swing.JLabel();
        MotorPHLogo = new javax.swing.JLabel();
        leaveRequestManagement = new javax.swing.JButton();
        attendanceeTracking = new javax.swing.JButton();
        empManagement = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        emppagemenuPNL1 = new javax.swing.JPanel();

        jPopupMenu1.setBackground(new java.awt.Color(0, 0, 0));
        jPopupMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jPopupMenu1.setToolTipText("MENU BAR");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));

        emppagemainPNL.setBackground(new java.awt.Color(255, 255, 255));
        emppagemainPNL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        emppagemainPNL.setForeground(new java.awt.Color(51, 51, 51));
        emppagemainPNL.setToolTipText("");
        emppagemainPNL.setLayout(null);

        emppagemenuPNL.setBackground(new java.awt.Color(208, 12, 12));
        emppagemenuPNL.setForeground(new java.awt.Color(51, 51, 55));

        javax.swing.GroupLayout emppagemenuPNLLayout = new javax.swing.GroupLayout(emppagemenuPNL);
        emppagemenuPNL.setLayout(emppagemenuPNLLayout);
        emppagemenuPNLLayout.setHorizontalGroup(
            emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        emppagemenuPNLLayout.setVerticalGroup(
            emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        emppagemainPNL.add(emppagemenuPNL);
        emppagemenuPNL.setBounds(0, 0, 70, 520);

        specialaccessPNL.setBackground(new java.awt.Color(158, 12, 12));
        specialaccessPNL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        specialaccessPNL.setForeground(new java.awt.Color(51, 51, 51));

        dateTime.setBackground(new java.awt.Color(0, 0, 0));
        dateTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateTime.setForeground(new java.awt.Color(255, 204, 204));
        dateTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateTime.setText("DD/MM/YYYY HH:MM:00");

        employeepagenameLBL.setBackground(new java.awt.Color(153, 0, 51));
        employeepagenameLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        employeepagenameLBL.setForeground(new java.awt.Color(255, 204, 204));
        employeepagenameLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeepagenameLBL.setText("Admin User");
        employeepagenameLBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        logoutemppgPB.setBackground(new java.awt.Color(128, 12, 12));
        logoutemppgPB.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        logoutemppgPB.setForeground(new java.awt.Color(255, 255, 255));
        logoutemppgPB.setText("Log out");
        logoutemppgPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutemppgPBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout specialaccessPNLLayout = new javax.swing.GroupLayout(specialaccessPNL);
        specialaccessPNL.setLayout(specialaccessPNLLayout);
        specialaccessPNLLayout.setHorizontalGroup(
            specialaccessPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, specialaccessPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeepagenameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(logoutemppgPB)
                .addGap(23, 23, 23))
        );
        specialaccessPNLLayout.setVerticalGroup(
            specialaccessPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialaccessPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(specialaccessPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTime)
                    .addComponent(employeepagenameLBL)
                    .addComponent(logoutemppgPB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        employeepagenameLBL.getAccessibleContext().setAccessibleName("");

        emppagemainPNL.add(specialaccessPNL);
        specialaccessPNL.setBounds(390, 430, 540, 40);

        aboutPB.setBackground(new java.awt.Color(153, 0, 0));
        aboutPB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        aboutPB.setForeground(new java.awt.Color(255, 255, 255));
        aboutPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/COMPANY 100 X 100.png"))); // NOI18N
        aboutPB.setText("About");
        aboutPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutPBActionPerformed(evt);
            }
        });
        emppagemainPNL.add(aboutPB);
        aboutPB.setBounds(190, 140, 200, 80);

        personaldetPB.setBackground(new java.awt.Color(153, 0, 0));
        personaldetPB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        personaldetPB.setForeground(new java.awt.Color(255, 255, 255));
        personaldetPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/DETAILS 64 X 64.png"))); // NOI18N
        personaldetPB.setText("View Details");
        personaldetPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personaldetPBActionPerformed(evt);
            }
        });
        emppagemainPNL.add(personaldetPB);
        personaldetPB.setBounds(410, 140, 200, 80);

        attendanceemppgPB.setBackground(new java.awt.Color(153, 0, 0));
        attendanceemppgPB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        attendanceemppgPB.setForeground(new java.awt.Color(255, 255, 255));
        attendanceemppgPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ATTENDANCE 64 X 64.png"))); // NOI18N
        attendanceemppgPB.setText("View Attendance");
        attendanceemppgPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceemppgPBActionPerformed(evt);
            }
        });
        emppagemainPNL.add(attendanceemppgPB);
        attendanceemppgPB.setBounds(190, 230, 200, 80);

        payrollemppgPB.setBackground(new java.awt.Color(153, 0, 0));
        payrollemppgPB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        payrollemppgPB.setForeground(new java.awt.Color(255, 255, 255));
        payrollemppgPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/PAYROLL 64 X 64.png"))); // NOI18N
        payrollemppgPB.setText("View Payroll");
        payrollemppgPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payrollemppgPBActionPerformed(evt);
            }
        });
        emppagemainPNL.add(payrollemppgPB);
        payrollemppgPB.setBounds(410, 230, 200, 80);

        requestleaveemppgPB.setBackground(new java.awt.Color(153, 0, 0));
        requestleaveemppgPB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        requestleaveemppgPB.setForeground(new java.awt.Color(255, 255, 255));
        requestleaveemppgPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/REQUEST LEAVE 64 X 64.png"))); // NOI18N
        requestleaveemppgPB.setText("Request Leave");
        requestleaveemppgPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestleaveemppgPBActionPerformed(evt);
            }
        });
        emppagemainPNL.add(requestleaveemppgPB);
        requestleaveemppgPB.setBounds(410, 320, 200, 80);

        redOrangeDesign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Red-Orange Design.png"))); // NOI18N
        redOrangeDesign.setText("RedOrangeDesign");
        redOrangeDesign.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        redOrangeDesign.setPreferredSize(new java.awt.Dimension(725, 500));
        emppagemainPNL.add(redOrangeDesign);
        redOrangeDesign.setBounds(-10, -20, 510, 500);

        lblWelcomeMessage.setBackground(new java.awt.Color(0, 0, 51));
        lblWelcomeMessage.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        lblWelcomeMessage.setForeground(new java.awt.Color(51, 0, 0));
        lblWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage.setText("Admin Dashboard");
        lblWelcomeMessage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblWelcomeMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        emppagemainPNL.add(lblWelcomeMessage);
        lblWelcomeMessage.setBounds(250, 47, 610, 60);
        lblWelcomeMessage.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10)); // Top, Left, Bottom, Right padding

        MotorPHLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/MotorLogo 81x84.png"))); // NOI18N
        emppagemainPNL.add(MotorPHLogo);
        MotorPHLogo.setBounds(790, 30, 100, 90);

        leaveRequestManagement.setBackground(new java.awt.Color(153, 0, 0));
        leaveRequestManagement.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        leaveRequestManagement.setForeground(new java.awt.Color(255, 255, 255));
        leaveRequestManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/REQUEST LEAVE 64 X 64.png"))); // NOI18N
        leaveRequestManagement.setText("Leave Request Management");
        leaveRequestManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveRequestManagementActionPerformed(evt);
            }
        });
        emppagemainPNL.add(leaveRequestManagement);
        leaveRequestManagement.setBounds(630, 320, 270, 80);

        attendanceeTracking.setBackground(new java.awt.Color(153, 0, 0));
        attendanceeTracking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        attendanceeTracking.setForeground(new java.awt.Color(255, 255, 255));
        attendanceeTracking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ATTENDANCE 64 X 64.png"))); // NOI18N
        attendanceeTracking.setText("Attendance Tracking");
        attendanceeTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceeTrackingActionPerformed(evt);
            }
        });
        emppagemainPNL.add(attendanceeTracking);
        attendanceeTracking.setBounds(630, 230, 270, 80);

        empManagement.setBackground(new java.awt.Color(153, 0, 0));
        empManagement.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empManagement.setForeground(new java.awt.Color(255, 255, 255));
        empManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/DETAILS 64 X 64.png"))); // NOI18N
        empManagement.setText("Employee Management");
        empManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empManagementActionPerformed(evt);
            }
        });
        emppagemainPNL.add(empManagement);
        empManagement.setBounds(630, 140, 270, 80);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Employee Name");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        emppagemainPNL.add(jLabel1);
        jLabel1.setBounds(480, 100, 138, 25);

        emppagemenuPNL1.setBackground(new java.awt.Color(188, 12, 12));
        emppagemenuPNL1.setForeground(new java.awt.Color(51, 51, 55));

        javax.swing.GroupLayout emppagemenuPNL1Layout = new javax.swing.GroupLayout(emppagemenuPNL1);
        emppagemenuPNL1.setLayout(emppagemenuPNL1Layout);
        emppagemenuPNL1Layout.setHorizontalGroup(
            emppagemenuPNL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        emppagemenuPNL1Layout.setVerticalGroup(
            emppagemenuPNL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        emppagemainPNL.add(emppagemenuPNL1);
        emppagemenuPNL1.setBounds(110, 0, 70, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(emppagemainPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(emppagemainPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutemppgPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutemppgPBActionPerformed
       
  
    }//GEN-LAST:event_logoutemppgPBActionPerformed

    private void aboutPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutPBActionPerformed
        // Redirect to AboutPage
    }//GEN-LAST:event_aboutPBActionPerformed

    private void personaldetPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personaldetPBActionPerformed
        // Redirect to Personal Details Page

    }//GEN-LAST:event_personaldetPBActionPerformed

    private void attendanceemppgPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceemppgPBActionPerformed
        // Redirect to Attendance Page

    }//GEN-LAST:event_attendanceemppgPBActionPerformed

    private void payrollemppgPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollemppgPBActionPerformed
        // Redirect to Payroll Employee View Page

    }//GEN-LAST:event_payrollemppgPBActionPerformed

    private void requestleaveemppgPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestleaveemppgPBActionPerformed
        // Redirect to Request Leave Page

    }//GEN-LAST:event_requestleaveemppgPBActionPerformed

    private void leaveRequestManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveRequestManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leaveRequestManagementActionPerformed

    private void attendanceeTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceeTrackingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendanceeTrackingActionPerformed

    private void empManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empManagementActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Metal look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    
  
    
    
    }

     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MotorPHLogo;
    private javax.swing.JButton aboutPB;
    private javax.swing.JButton attendanceeTracking;
    private javax.swing.JButton attendanceemppgPB;
    private javax.swing.JLabel dateTime;
    private javax.swing.JButton empManagement;
    private javax.swing.JLabel employeepagenameLBL;
    private javax.swing.JPanel emppagemainPNL;
    private javax.swing.JPanel emppagemenuPNL;
    private javax.swing.JPanel emppagemenuPNL1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JButton leaveRequestManagement;
    private javax.swing.JButton logoutemppgPB;
    private javax.swing.JButton payrollemppgPB;
    private javax.swing.JButton personaldetPB;
    private javax.swing.JLabel redOrangeDesign;
    private javax.swing.JButton requestleaveemppgPB;
    private javax.swing.JPanel specialaccessPNL;
    // End of variables declaration//GEN-END:variables
}
